spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: localhost
    port: 2525
    username: checkmate@chess.be
    password: ILoveChess
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true