spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 2525
    username: checkmate@chess.be
    password: ILoveChess
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true